name: Pull Latest Changes

on:
  push:
    branches:
      - main  # Replace with the branch you want to monitor

jobs:
  pull:
    runs-on: ubuntu-latest  # You can choose the appropriate runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Pull Latest Changes
        run: git pull origin main  # Replace "main" with the branch you want to pull from

